apiVersion: v1
kind: Pod
metadata:
   name: nginx-pod
   lables:
    app: nginx
#container create inpod 
spec:
  containers:
    - name: mycontainer
      image: nginx:latest
      ports: 
        - containerPort: 80
