apiVersion: v1
kind:  ReplicationController
metadata:
   name: nginx-replicas
spec:
    replicas: 4
    selector:
      app: nginx
templeta:
  metadata:
    labels:
     app: nginx
  spec:
    containers:
      - ports: 
          containerPort: 80
        name: nginx-replicas
        image: nginx