apiVersion: apps/v1
kind: ReplicaSet
metadata:
   name: nginx-replicas
   labels:
    app: shraa
spec:
    replicas: 4
    selector:
     # matchLabels:
     #    app: nginx
      matchExpressions:
        - {key: app, operator: In, values: [shraa , aru]}
    template:
      metadata:
        name: shraa
        labels:
          app: aru 
          #env: shraa
      spec:
        containers:
          - name: nginx-replicas
            image: nginx
            ports: 
             - containerPort: 80